### ISSUE TITLE
Does python IDLE work on Windows 10 Home Edition.  Setup fails.  See attached.

### ISSUE THREAD

**Issue by ligockij** [proevo/pythondotorg#1872]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots*
![thumbnail_image](https://user-images.githubusercontent.com/91220660/134407154-4f7e1312-25c1-4705-be7d-ab1b15a9aa76.png)
*

[Python 3.9.7 (64-bit)_20210921211706.log](https://github.com/python/pythondotorg/files/7213195/Python.3.9.7.64-bit._20210921211706.log)
**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by mwichmann** [comment]
The reason the errors are terse is that the WIndows installation system is sometimes extremely inscrutible and gives you back these hexadecimal codes. Usually you need to repair something at that point that's outside the control of the program you're trying to install.

**Comment by ned-deily** [comment]
@ligockij Thanks for the report but this issue tracker is for issues with the python.org website rather than for issues with Python use or installation. You would likely have received faster and more complete help using one of the resources on the [python.org help page](https://www.python.org/about/help/).
