### ISSUE TITLE
CRC mismatch

### ISSUE THREAD

**Issue by timmjd** [proevo/pythondotorg#1935]
**Describe the bug**
CRC missmatch for old Python 2.4.x versions

```
python-2.4.msi   [ e9fe1fcdce9fa8c5590ab58b1de3246f != 5810ed46da712adef93315b08791aea8 (EXPECTED) ]
python-2.4.4.msi [ 8b1517fdbf287d402ac06cc809abfad6 != e153f8e72e53b34694323321d1a6654c (EXPECTED) ]
python-2.4.3.msi [ ab946459d7cfba4a8500f9ff8d35cc97 != 9a06d08854ddffc85d8abd11f3c2acc2 (EXPECTED) ]
python-2.4.2.msi [ bfb6fc0704d225c7a86d4ba8c922c7f5 != f9a189a11316dc523732b38334c9dd7b (EXPECTED) ]
```

**To Reproduce**
1. Go to https://www.python.org/downloads/
2. Click on version 2.4 / 2.4.4 / 2.4.3 / 2.4.2
3. Select windows MSI installer
4. Download
5. Check MD5 against MD5 mentioned on webpage

**Expected behavior**
MD5 does match

**Comment by ned-deily** [comment]
@berkerpeksag, it looks you updated those release pages for some reason back in 2017?

**Comment by hugovk** [comment]
I get these values, which match those on the pages listed under "Files, MD5 checksums, signatures and sizes":

| page | download | md5 |
| - | - | - |
| https://www.python.org/downloads/release/python-240/ |https://www.python.org/ftp/python/2.4/python-2.4.msi | e9fe1fcdce9fa8c5590ab58b1de3246f  |
| https://www.python.org/downloads/release/python-244/ | https://www.python.org/ftp/python/2.4.4/python-2.4.4.msi | 8b1517fdbf287d402ac06cc809abfad6 |
| https://www.python.org/downloads/release/python-243/ | https://www.python.org/ftp/python/2.4.3/python-2.4.3.msi | ab946459d7cfba4a8500f9ff8d35cc97 |
| https://www.python.org/downloads/release/python-242/ | https://www.python.org/ftp/python/2.4.2/python-2.4.2.msi | bfb6fc0704d225c7a86d4ba8c922c7f5 |

---

The problem is the pages list also md5 values in the table at the bottom, and it shows the `python-2.4*.msi` file but the `python-2.4*.ia64.msi` checksum. For example, https://www.python.org/downloads/release/python-240/:

<img width="1183" alt="image" src="https://github.com/user-attachments/assets/87f22f8b-e120-418d-8206-6bdc1879e51d">

We should show e9fe1fcdce9fa8c5590ab58b1de3246f in the table next to "Windows x86 MSI installer", which links to https://www.python.org/ftp/python/2.4/python-2.4.msi.

**Comment by hugovk** [comment]
I've updated the md5 in the tables to match. For example,  https://www.python.org/downloads/release/python-240/:

For example, 
<img width="1180" alt="image" src="https://github.com/user-attachments/assets/c8cbd90a-8a27-4a07-85c2-f8bb6d63e3ee">
