### ISSUE TITLE
Documentation download pages have broken URLs

### ISSUE THREAD

**Issue by paulehoffman** [proevo/pythondotorg#2243]
**Describe the bug**
The pages for downloading Python documentation, such as [for 3.11](https://docs.python.org/release/3.11.1/download.html), have URLs to the documents whose hosts are at `docs.python.org`. All those files get a 404 response. The URLs should have `www.python.org` as the host; those links would work.

**To Reproduce**
1. Go to https://docs.python.org/3/
2. Click on 'Download these documents' at the upper left
3. Click on any link in the table
4. See the 404

**Expected behavior**
The files should download instead of getting a 404.

**Desktop (please complete the following information):**
 - Browser: all

**Additional context**
You can go to the file index pages such as [here ](https://www.python.org/ftp/python/doc/3.11.1/) and the links work fine.

**Comment by ned-deily** [comment]
Thanks for the report. There is a problem but it's more complicated than what's stated. There are two sets of documentation links here: (1) the documents that are built at least daily for the current HEADs of pre-release and stable branches (currently 3.12/main, 3.11, and 3.10); (2) the documentation set built and published for each release (i.e. 3.11.1, etc and summarized [here](https://www.python.org/doc/versions/)). The problem is with the downloadable files for the latter, not the nightly builds (the downloads for the nightly builds like at https://docs.python.org/3/ appear to work correctly contrary to what is stated). IIRC, for backwards compatibility, there are supposed to be some redirects in place to allow the specific release build doc set downloads to work for both older and newer releases but that appears to not be working. (As I recall, the compatibility issues arose when the daily docs building and serving was moved to a separate host and domain some years back.) If someone doesn't get to it first, I'll try to investigate further. In the meantime, one can download the daily docs with the understanding that they might contain doc changes for as yet unreleased code changes or for a newer release if you are not using the most current release of a particular version.

**Comment by paulehoffman** [comment]
Seems fixed.

**Comment by ned-deily** [comment]
For the record, addressed here: https://github.com/python/cpython/issues/95290
