### ISSUE TITLE
"Volunteer for the PSF" page not found

### ISSUE THREAD

**Issue by thibaudcolas** [proevo/pythondotorg#2250]
Similar issue to #2210. On the [PSF landing page](https://www.python.org/psf-landing/), under the "Volunteer" menu, the "Volunteer for the PSF" link points to https://www.python.org/psf/volunteer/psf. This shows a "Error 404: File not Found".

**To Reproduce**

1. Go to[ '...'](https://www.python.org/psf-landing/)
2. Hover "Volunteer"
3. Click on "Volunteer for the PSF"

**Comment by juanpflores** [comment]
Can confirm this issue is still visible: 
![image](https://github.com/python/pythondotorg/assets/6200135/0dbeece9-a3c1-4924-9bf0-4bbde8a0b255)

---

Is interesting, I've been looking for the item under [fixtures/sitetree_menus.json](https://github.com/python/pythondotorg/blob/main/fixtures/sitetree_menus.json) and was not able to find the element for this specific menu item. The closest thing is the main [volunteer](https://github.com/python/pythondotorg/blob/c4ee749942227ca75c8e670546afe67232d647b2/fixtures/sitetree_menus.json#L1430C17-L1430C17) menu.

**Comment by Jmetrics86** [comment]
Confirming that this url is still 404: (I found it in the main menu)
https://www.python.org/psf/volunteer/psf
![image](https://github.com/python/pythondotorg/assets/19334741/1707a1f8-9062-4cd6-a7f6-c94ade25f155)


and this is the correct URL with a picture of the correct UI element to be clicked
https://www.python.org/psf/volunteer/
![image](https://github.com/python/pythondotorg/assets/19334741/9c267bff-c84e-4e4a-9dae-cc2a1d47e038)

**Comment by JacobCoffee** [comment]
This is configured via https://django-sitetree.readthedocs.io/en/latest/ so it isn't codified or able to be changed by anyone but an admin.

I fixed the link and it should be rolling out shortly.

Thanks for the report!
