### ISSUE TITLE
Remove link to facebook and add LinkedIn in the Python.org socialize menu

### ISSUE THREAD

**Issue by riecatnor** [proevo/pythondotorg#2325]
Along the same lines as issue #2322 I would suggest making two more small changes to the Socialize menu:
- Remove the Facebook link, the last post being almost 10 years ago (March 2014) it is effectively dormant and doesn't make sense to send folks there, imo.  
- Add a link to the [PSF LinkedIn page](https://www.linkedin.com/company/thepsf), which is active and has a significant following (127k followers).

**Comment by hugovk** [comment]
@mlcohen Feel up for doing some more icon magic? :)

**Comment by mlcohen** [comment]
> Feel up for doing some more icon magic?

Yeah, definitely! Happy to help. I'll find some time to work on this.

**Comment by sahanasurapureddy** [comment]
could you assign me this issue?

**Comment by hugovk** [comment]
@sahanasurapureddy No, we usually don't assign issues because sometimes people disappear and then the next person doesn't know if they're still working on it or not. 

And in this case, see the message directly above yours: someone else is planning on doing this. Let's give them a chance first. Thanks!

**Comment by hugovk** [comment]
https://github.com/python/pythondotorg/pull/2327 was superseded by https://github.com/python/pythondotorg/pull/2367 which has been merged.
